
// This is an auto-generated test file
// Generated by src/test/test_generator.py
//
// Last Modified: December 09 2013 01:46PM

extern mod re;

macro_rules! run_tests(
  ($re: expr, $input: expr, $expect: pat) => (
    {
      let mut re = UncompiledRegexp::new($re);
      match re.run($input) {
        $expect => assert!(true),
        _ => assert!(false)
      }
    }
  )
)

#[cfg(test)]
mod python_tests {
  use re::UncompiledRegexp;

  // Tests start here
  
  #[test]
  fn test_case_ident_0() {
    run_tests!("[^^]+", "abc", Some(_))
  }

  #[test]
  fn test_case_ident_1() {
    run_tests!("[^^]+", "^", None)
  }

  #[test]
  fn test_case_ident_2() {
    run_tests!("[^al-obc]+", "kpd", Some(_))
  }

  #[test]
  fn test_case_ident_3() {
    run_tests!("[^al-obc]+", "abc", None)
  }

  #[test]
  fn test_case_ident_4() {
    run_tests!("[al-obc]+", "almocb", Some(_))
  }

  #[test]
  fn test_case_ident_5() {
    run_tests!("[al-obc]+", "defzx", None)
  }

  #[test]
  fn test_case_ident_6() {
    run_tests!("a(?:b|c|d)(.)", "ace", Some(_))
  }

  #[test]
  fn test_case_ident_7() {
    run_tests!("a(?:b|c|d)*(.)", "ace", Some(_))
  }

  #[test]
  fn test_case_ident_8() {
    run_tests!("a(?:b|c|d)+?(.)", "ace", Some(_))
  }

}
